### ISSUE TITLE
Add the <mdrpi:PublicationInfo> extension element

### ISSUE THREAD

**Issue by trscavo** [iay/mdq-server#22]
Add an `<mdrpi:PublicationInfo>` extension element to the `/entities` aggregate as well as the `/entities/collection:idps` aggregate. Likewise add this extension element to each signed entity descriptor. In all cases, set the `publisher` XML attribute to the location of the aggregate or entity metadata.

**Comment by iay** [comment]
Again, anything which would be an InCommon-specific configuration issue should go on the `mdq-server-docker` project, not this one. I'll comment here, though, to save time.

I think I understand you to be asking for the `publisher` attribute to be different for every individual signed entity response as well as for each aggregate, as all of these things have different locations. This would be almost impossible to do with the current implementation, as all signed content runs through the same pipeline, and there's no way to inject variable content into that. In addition, the pipeline is not executed in a context where it knows the location used, nor is it always the same unless you separate the SHA1-transformed identifiers from the untransformed ones.

In addition, I'm personally of the opinion that this runs against the intent of the MDRPI specification, expressed thus:

> **publisher**: A unique identifier for the publisher of the metadata. This may be the location from which the metadata was retrieved, an abstract identifier such as a SAML entity ID, or some other unique identifier for the publisher.

I believe that in this kind of case, using the location as a unique identifier *for the publisher* only makes sense if the location is the same for all of the responses (the different responses do not come from different publishers). Following the intent of the specification in this context would involve picking as unique publisher ID either:

* A single URI representing InCommon (e.g., `http://incommon.org`)
* A single URI representing the MDQ instance (e.g., `http://mdq-beta.incommon.org/global`)

Such a change would be very simple to implement, of course.

**Comment by trscavo** [comment]
Again my bad. I moved this issue to the correct project: https://github.com/iay/mdq-server-docker/issues/15

This time I tried to be less prescriptive :-)
