### ISSUE TITLE
Explicit <mdrpi:RegistrationInfo> elements will be added to InCommon metadata

### ISSUE THREAD

**Issue by trscavo** [iay/mdq-server#23]
This is just a heads up! Not sure if this requires any further action.

InCommon Operations will add explicit `<mdrpi:RegistrationInfo>` elements to production metadata according to the following schedule:

1. preview aggregate: Wed, Feb 4, 2015
2. main aggregate: Wed, Feb 11, 2015
3. fallback aggregate: Web, Feb 18, 2015

I assume the mdq-server instance at mdq-beta.incommon.org is consuming the main (production) aggregate, in which case the middle date above is most relevant.

**Comment by iay** [comment]
If there was an issue, it would be on [`iay/mdq-server-docker`](https://github.com/iay/mdq-server-docker), as that's where the InCommon-specific configuration lives.

However, I'm fairly sure that it will just work, as the configuration adds `<mdrpi:RegistrationInfo>` for InCommon entities only if they are not already present (see [`config.xml`](https://github.com/iay/mdq-server-docker/blob/master/incommon/resources/config.xml) around line 102). I will do a specific test against your preview aggregate some time before the 4th and 11th though, just to make sure.

**Comment by trscavo** [comment]
My bad. I moved this (non-)issue to the correct project: https://github.com/iay/mdq-server-docker/issues/14
