### ISSUE TITLE
AD FS cannot load metadata for entities with forward slashes in their IDs

### ISSUE THREAD

**Issue by xenophonf** [iay/mdq-server#38]
Given an mdq-server deployment accessible over HTTPS, Active Directory Federation Services versions 2.0 and 3.0 cannot download metadata for entities with the `/` (forward slash) character in their entity IDs.  This happens because AD FS converts all occurrences of `%2F` in the URL-encoded (a/k/a percent-encoded) entity ID back into the `/` character, causing mdq-server to reject the entity metadata query with a HTTP 404 (not found) response.

To give a concrete example, assume a base URL of `https://mdq.example.com/entities/` and a URL-encoded entity ID of `https%3a%2f%2fidp.example.com%2fshibboleth`.  Configure a new claims provider trust in AD FS using the metadata URL of `https://mdq.example.com/entities/https%3a%2f%2fidp.example.com%2fshibboleth`.  When it attempts to load the metadata, it will issue the following HTTP request: `GET /entities/https%3a//idp.example.com/shibboleth`.

**Comment by nckroy** [comment]
This seems like ADFS is not doing URL encoding correctly, that seems like an ADFS bug.

**Comment by trscavo** [comment]
> This seems like ADFS is not doing URL encoding correctly, that seems like an ADFS bug

+1

The Metadata Query Protocol spec (which admittedly only an Internet Draft) is pretty clear about this.

**Comment by iay** [comment]
It looks like AD FS is not so much doing URL encoding incorrectly, as that it is performing a URL *decoding* step when it shouldn't. Same effect, though, I suppose.

I hesitate to suggest it, but given that these URLs are (I assume) not being dynamically generated, it might be possible to try over-encoding the `%` characters as `%25` to see if you can sneak them in that way. Worth a try?

**Comment by iay** [comment]
I also find it curious that it is leaving the `:` encoded as `%3a` while decoding the `/` characters. Or perhaps it is decoding all of them and then re-encoding the `:`.

**Comment by xenophonf** [comment]
@iay, I suspect that AD FS performs a URL canonicalization step somewhere, hence the decoding of the escaped slashes.  I tried escaping the `%` characters as `%25`, e.g., `https://mdq.example.com/entities/https%3a%252f%252fidp.example.com%252fshibboleth`, but AD FS ended up sending `%252f`.  If I used a form of the URL where the entity ID was specified as a query string, e.g., `https://mdq.example.com/entities/?id=https%3a%2f%2fidp.example.com%2fshibboleth`---and yes, I'm aware this isn't allowed by the MDQ protocol specification, but I had the packet captures going and thought this might shed some light on how AD FS implements its metadata update mechanism---AD FS sends the query string unchanged, e.g., `GET /entities/?id=https%3a%2f%2fidp.example.com%2fshibboleth`.

**Comment by iay** [comment]
Thanks for checking that, seems like we have enough insight into what AD FS is doing now to know that we can't just fool it into doing the right thing. To be honest, URL canonicalisation isn't a completely unreasonable thing to do with user input, so unless Microsoft were claiming that they support MDQ then it's hard to call this a bug on their part.

What to do next depends on your use case, I think. If you're just trying to get AD FS to read one particular entity descriptor using MDQ to an `mdq-server` deployment, probably the easiest thing to try next would be to use the SHA-1 identifier alias the MDQ specification requires to be present for SAML metadata:

````
.../entities/{sha1}12313134123....123123
````

That doesn't contain any problematic characters so should survive any normalisation AD FS is doing. It can be annoying to compute the hash directly, but if you just visit the normally-encdoded endpoint with a browser you should see the alternate identifier in the human-readable output:

````
Identifiers: 2

   * https://idp2.iay.org.uk/idp/shibboleth
   * {sha1}8dceff94e7b25f33596fe33e6e1543387bd373b0
````

For example, visit <http://md.iay.org.uk/static/entities/{sha1}8dceff94e7b25f33596fe33e6e1543387bd373b0>

If your use case is a local oracle for AD FS clients, then another option would be to provide additional AD FS-friendly identifiers for each entity, for example by adding another transformer to the `ItemIdTransformStage` in the source pipeline following the one [here](https://github.com/iay/mdq-server/blob/master/src/main/resources/config.xml#L35) (or at the appropriate location in your own configuration). Those transformers are implementations of the Spring Framework `Converter<String, String>` interface and are basically one-liners. A generic regular expression replacement one might be a decent thing to implement as part of the standard Shibboleth MDA repertoire, in fact, so I will raise a JIRA ticket to consider that.

What I have in mind here would be a item ID converter that replaced, say, `%2f` with `-` throughout. As I say, what you want probably depends on your use case, so I can probably help more if I understand that.

**Comment by iay** [comment]
Added a [JIRA ticket](https://issues.shibboleth.net/jira/browse/INFRA-155).

**Comment by xenophonf** [comment]
@nckroy, @trscavo: I'm not sure this is a bug in AD FS.  It's more like a differing interpretation of RFC 2396 *et subseq.*  I skimmed through them, and it isn't completely clear to me how escaped forward slashes in the absolute path portion of a URL *must* be canonicalized.  Those RFCs do seem to imply that two otherwise identical absolute paths, one with escaped forward slashes and one without, *may* (or even *should*) have the same semantics.  When I read mdq-server's source code for EntitiesController, MetadataService, and ItemCollectionLibrary, I expected them (or Spring above them) to decode the identifier, e.g., `https://idp.example.com/shibboleth`, and use the decoded identifier for hashtable lookups (that doesn't seem to be how they work).  In that case it wouldn't matter if slashes were URL-encoded or not, as long as the final representation of the entity identifier is the canonical, unescaped one.

**Comment by xenophonf** [comment]
I am deploying several SharePoint web application servers as part of a VRO project at NIH/NIAID.  SharePoint only supports WS-Federation, so we must use AD FS to translate between the SharePoint STS and SAML-based identity federations.  Due to regulatory requirements we require that federated logins provide ePPN and mail claims.  In order to guarantee that IdPs will release those attributes to us, we are applying for the REFEDS R&S classification on our AD FS service providers.  InCommon requires that R&S-classified service providers update metadata on a daily basis.

AD FS version 2.0 and 3.0 cannot read the federation metadata aggregates published by InCommon, eduGAIN, and others, as it expects claims provider or relying party trust relationships to be configured singly.  In order to load (or update) federation metadata into AD FS, one generally downloads a suitable aggregate, verifies it somehow, extracts the desired `EntityDescriptor` elements, and creates the appropriate trust relationships using the extracted metadata.  This is basically how both [sila](http://sila.codeplex.com/) and [pysFemma](https://github.com/rohe/pysfemma) work.  However, these tools duplicate AD FS functionality in that (1) mdq-server makes per-entity metadata available over HTTP and (2) AD FS can monitor (and automatically update) an entity's metadata if it's published singly over HTTPS---AD FS relies on X.509 PKI to bootstrap trust.

So, with that as the background, I have mdq-server accessible over HTTPS, and I have written a simple PowerShell script that walks the `/x-entity-list` endpoint and creates claims provider trust relationships on my AD FS service providers for each of the listed identity providers.  The script only needs to track the addition or deletion of identity providers and thus add or remove claims provider trust relationships accordingly.  AD FS itself handles metadata updates (key rollover, SAML endpoint changes, etc.) for existing claims provider trust relationships.

**Comment by xenophonf** [comment]
How would I go about obtaining a SHA-1 entity ID programmatically?  It isn't in the JSON entity list, nor is it in the XML metadata for a given entity.  It also isn't simply a hash of the entity ID.  Without having seen the source code for `net.shibboleth.metadata.pipeline.MDQuerySHA1ItemIdTransformer`, I'm assuming that I could compute it locally.

**Comment by iay** [comment]
It should be "{sha1}" followed by a lower-case hex representation of the SHA-1 hash of the entity ID.

**Comment by xenophonf** [comment]
Oh, I see what I was doing wrong.  I was running `echo ... | shasum` instead of `echo -n ... | shasum`.  Thanks for the hint, @iay!

**Comment by xenophonf** [comment]
Somehow curl manages to get this wrong:

```tcsh
> curl --silent 'https://mdq-dev.ibrsp.org/global/entities/{sha1}14a816df69ea778da34b1ca44ece970374d17148'
{
  "timestamp" : 1455913604639,
  "status" : 404,
  "error" : "Not Found",
  "message" : "Not Found",
  "path" : "/global/entities/sha114a816df69ea778da34b1ca44ece970374d17148"
}
```

Fortunately, wget works properly:

```tcsh
> wget 'https://mdq-dev.ibrsp.org/global/entities/{sha1}14a816df69ea778da34b1ca44ece970374d17148'
--2016-02-19 15:25:05--  https://mdq-dev.ibrsp.org/global/entities/%7Bsha1%7D14a816df69ea778da34b1ca44ece970374d17148
Resolving mdq-dev.ibrsp.org (mdq-dev.ibrsp.org)... 52.50.3.89
Connecting to mdq-dev.ibrsp.org (mdq-dev.ibrsp.org)|52.50.3.89|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 12222 (12K) [application/samlmetadata+xml]
Saving to: ‘{sha1}14a816df69ea778da34b1ca44ece970374d17148’

{sha1}14a816df69ea778da34b1ca44ece970374d17 100%[===========================================================================================>]  11.94K  45.0KB/s    in 0.3s    

2016-02-19 15:25:07 (45.0 KB/s) - ‘{sha1}14a816df69ea778da34b1ca44ece970374d17148’ saved [12222/12222]
```

**Comment by xenophonf** [comment]
Using the SHA-1 hash as the entity identifier works for me!  I successfully tested creating a claims provider trust relationship on both AD FS 2.0 and 3.0.  Thanks again, @iay!  I'll leave it up to you as to whether to close this issue.

**Comment by iay** [comment]
I'd like to capture the conclusions if at all possible before closing this. @xenophonf: the wiki is enabled on this project, would you be prepared to put a brief writeup there for the next person going down this road?

**Comment by xenophonf** [comment]
The below PowerShell script adds claims provider trusts based on data provided by mdq-server.  Extending it to relying parties is left as an exercise left to the reader.  Key features:

- will add or remove trusts based on changes to the metadata feed presented by mdq-server (using the `Notes` field to track this)

- adds claim acceptance transform rules, e.g., for converting ePPN and mail attributes into AD FS claims

Note that mdq-server must be accessible over HTTPS in order for it to work with AD FS.

```powershell
## uncomment the following if using AD FS 2.0
#Add-PSSnapin Microsoft.Adfs.PowerShell

## base URL of MDQ service
$mdqBaseUri = "https://mdq.example.com/global"

## acceptance transform rules
$rules = '
@RuleName = "Transform ePPN to UPN"
c:[Type == "urn:oid:1.3.6.1.4.1.5923.1.1.1.6"]
 => issue(Type = "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/upn", Issuer = c.Issuer, OriginalIssuer = c.OriginalIssuer, Value = c
.Value, ValueType = c.ValueType);

@RuleName = "Transform mail to mail"
c:[Type == "urn:oid:0.9.2342.19200300.100.1.3"]
 => issue(Type = "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress", Issuer = c.Issuer, OriginalIssuer = c.OriginalIssuer, 
Value = c.Value, ValueType = c.ValueType);
'

## tag federated claims providers by putting the following in the
## `Notes` field
$notes = "DO NOT CHANGE THIS TEXT - Federated IdP - C992C076-D84D-11E5-ACFB-F6D137852114"

## get list of existing claims providers
$existing_cp_trusts = @(Get-ADFSClaimsProviderTrust | ForEach-Object { $_.Identifier } )

$federated_entities = @()
$count = -1
$sha1 = New-Object -TypeName System.Security.Cryptography.SHA1CryptoServiceProvider
$utf8enc = New-Object -TypeName System.Text.UTF8Encoding
$entities = Invoke-RestMethod -Uri "$mdqBaseUri/x-entity-list" -Method Get
foreach ($entity in $entities)
{
  ## uncomment the following for some debugging output
  #$count++
  #Write-Host $entity.entityID
  #Write-Host $count

  ## make list of federated entity IDs (used later to remove
  ## decommissioned IdPs)
  $federated_entities += $entity.entityID

  ## skip entity if already configured
  if ($existing_cp_trusts -contains $entity.entityID) { continue }

  ## display name defaults to entity ID
  $displayName = $entity.entityID

  ## must be an identity provider
  $not_idp = $true
  foreach ($role in $entity.roles)
  {
    if ($role.type -eq 'IDPSSODescriptor')
    {
      $not_idp = $false
      if ($role.displayName -ne $null)
      {
        ## assumes that this is the display name in the home
        ## system's language
        $displayName = $role.displayName
      }
      break
    }
  }
  if ($not_idp) { continue }

  ## compute the SHA-1 hash of the entity ID
  $hashedEntityId = [System.BitConverter]::ToString(
    $sha1.ComputeHash(
      $utf8enc.GetBytes($entity.entityID))).Replace("-", "").ToLower()

  ## download the entity's metadata
  $metadataUrl = "$mdqBaseUri/entities/{sha1}$hashedEntityId"
  $metadata = Invoke-RestMethod -Uri $metadataUrl -Method Get

  ## must not be blacklisted
  ## https://spaces.internet2.edu/display/InCFederation/Hide+From+Discovery+Category
  $blacklisted = $false
  foreach ($entityAttribute in $metadata.EntityDescriptor.Extensions.EntityAttributes.Attribute)
  {
    if ($entityAttribute.Name -eq 'http://macedir.org/entity-category' `
        -and $entityAttribute.NameFormat -eq 'urn:oasis:names:tc:SAML:2.0:attrname-format:uri' `
        -and $entityAttribute.AttributeValue -eq 'http://refeds.org/category/hide-from-discovery')
    {
      $blacklisted = $true
      break
    }
  }
  if ($blacklisted) { continue }

  ## must release REFEDS R&S attributes
  ## https://spaces.internet2.edu/display/InCFederation/Research+and+Scholarship+Category
  $not_rs = $true
  foreach ($entityAttribute in $metadata.EntityDescriptor.Extensions.EntityAttributes.Attribute)
  {
    if ($entityAttribute.Name -eq 'http://macedir.org/entity-category-support' `
        -and $entityAttribute.NameFormat -eq 'urn:oasis:names:tc:SAML:2.0:attrname-format:uri' `
        -and ($entityAttribute.AttributeValue -eq 'http://id.incommon.org/category/research-and-scholarship' `
              -or $entityAttribute.AttributeValue -eq 'http://refeds.org/category/research-and-scholarship'))
    {
      $not_rs = $false
      break
    }
  }
  if ($not_rs) { continue }

  ## create a new claims provider trust
  Add-AdfsClaimsProviderTrust -Name $displayName -MetadataUrl $metadataUrl -MonitoringEnabled:$true -AutoUpdateEnabled:$true -AcceptanceTransformRules $rules -Notes $notes
}

## get list of federation members' CP trusts
$federated_cp_trusts = @(Get-ADFSClaimsProviderTrust | ForEach-Object {
  if ($_.Notes -eq $notes) { $_.Identifier } } )

## remove any that aren't listed in the metadata feed
foreach ($cptrust in $federated_cp_trusts)
{
  if ($federated_entities -notcontains $cptrust)
  {
    Remove-AdfsClaimsProviderTrust -TargetIdentifier $entity
  }
}
```
